#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app


FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Microservice.Report/Microservice.Report.csproj", "Microservice.Report/"]
RUN dotnet restore "Microservice.Report/Microservice.Report.csproj"
COPY . .
WORKDIR "/src/Microservice.Report"
RUN dotnet build "Microservice.Report.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Microservice.Report.csproj" -c Release -o /app/publish /p:UseAppHost=false

EXPOSE 5000
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Microservice.Report.dll"]